#白名单QQ
whiteQQ:
  - 123456

#黑名单QQ
blackQQ:
  - 123456

#白名单禁言自动解禁
noBan: false

# 投票禁言开关
VoteBan: true
# 投票踢人开关
VoteKick: false
# 投票禁言超时时间 单位：秒
outTime: 180
# 投票最低所需票数 不建议太低
minNum: 4
# 投票成功禁言时间 单位：秒
BanTime: 3600
# 是否允许管理员一票否决
veto: true
# 是否允许投票禁言管理员(Bot为群主的情况下)
voteAdmin: false

groupVerify:
  #开启的群聊
  openGroup:
    - 123456
  # 如需要分群，请按照下列格式添加 <以群号为字段> 的成功提示即可，0 字段代表默认回复
  SuccessMsgs:
    254974507: ✅ 验证成功，欢迎入群，群里有非常多的大佬给你透哦~~
    0: ✅ 验证成功，欢迎入群

  # 答案验证模式，可选：精确、模糊
  mode: 精确
  # 最多允许尝试次数
  times: 7
  # 是否开启最后一分钟提醒（仅在超时时长大于等于 120 秒时有效，true 开启，false 关闭）
  remindAtLastMinute: true
  # 超时时长（秒），建议至少一分钟（60 秒）
  time: 300
  # 随机算式的数字的随机范围
  range:
    min: 10
    max: 100
  #收到进群事件后延迟多少秒再发送验证信息(秒)
  DelayTime: 2

groupAddNotice:
  openGroup:
    - 123465
  msg: 有一个加群通知，管理员快去看看吧~

# 撤回消息权限
# all: 所有人
# admin: 管理员 + 群主 + 主人
# owner: 群主 + 主人
# master: 主人
recallMsgPer:
  # 撤回bot消息
  bot: all
  # 撤回群员消息
  member: admin
