#是否只有主人能用
isMasterUse: false
#是否允许私聊使用
allowPM: true
#每名用户每日搜索次数限制
limit: 30
#SauceNAO搜图apikey 请在 https://saucenao.com/user.php?page=search-api 进行获取
SauceNAOApiKey:
#SauceNAO搜图相似度低于这个百分比将被认定为相似度过低
SauceNAOMinSim: 60
#saucanao 得到 NSFW 结果时隐藏缩略图，可选 0~3，严格程度依次增加
#0-不隐藏，1-隐藏明确为 NSFW 的缩略图，2-隐藏明确和可能为 NSFW 的缩略图，3-只显示明确为非 NSFW 的缩略图
hideImgWhenSaucenaoNSFW: 0
#绕过 Cloudflare Challenge 所使用的 TLS 版本，建议可选值：["TLSv1.1", "TLSv1.2"]
cfTLSVersion: TLSv1.1
#是否使用 Puppeteer 请求 ascii2d 以绕过 cf js challenge 注：该功能需安装puppeteer-extra 和 puppeteer-extra-plugin-stealth 依赖
ascii2dUsePuppeteer: false
#ascii2d搜图返回结果的最大数量
ascii2dResultMaxQuantity: 3
#隐藏所有搜索结果的缩略图
hideImg: false
#whatanime 得到 R18 结果时隐藏结果缩略图
hideImgWhenWhatanimeR18: false
#whatanime 发送预览视频，R18 结果不会发送
whatanimeSendVideo: false
# 是否在 saucenao 相似度过低时自动使用 ascii2d
useAscii2dWhenLowAcc: true
# 是否在 saucenao 搜索失败时自动使用 ascii2d
useAscii2dWhenFailed: true
