#是否允许私聊使用
allowPM: true
#是否排除 AI 作品
excludeAI: false
#获取张数大于前面的数时则使用对应的图片大小 可选值: ['mini', 'thumb', 'small', 'regular', 'original']
imgSize:
  6: 'regular'
  # 9: 'small'
  # 15: 'thumb'
#每名用户每日次数限制（0 则无限制）
limit: 30
#每个群和私聊的默认设置，单独设置后则失效，时间单位: 秒(s)
defSet:
  r18: 0 #1开启0关闭
  recall: 120 #撤回时间
  cd: 300 
