# 测试访问的网址列表（可空）设置为true或default将使用默认配置
# show: 是否显示 true - 显示 - false - 不显示 pro - 只有pro显示
# name: 显示名称
# url: 要访问的网址
# timeout: 测试超时时间
# useProxy: 是否使用插件配置中的代理访问
psTestSites:
  show: pro
  list:
    - name: Baidu
      url: https://baidu.com
      useProxy: true
    - name: Google
      url: https://google.com
      useProxy: true
  timeout: 5000

# 监控任务 该配置均需重启生效
monitor:
  # 是否开启监控任务
  open: true
  # 获取数据的间隔时间，单位为毫秒 间隔越短获取的数据越精确
  getDataInterval: 60000
  # 存储的数据数量，当数据量超出此值时会将最旧的数据删除
  saveDataNumber: 60
  # 如果出现内存异常的情况可将此配置项开启，如果打开后报错请将监控任务关闭
  statusPowerShellStart: false

# 背景图片api，设置为false则一直使用默认背景
# 默认地址 https://t.alcy.cc/mp
backdrop: "https://t.alcy.cc/mp"

# 当api请求失败时使用的默认背景图，请放置在resources/state/img/bg目录下
# random - 随机选择state/img/bg目录里的一张图片
# default_bg.jpg 可直接指定bg目录里一张图片，注意请带上后缀名
backdropDefault: "random"

# 显示的系统资源可选值: [CPU, RAM, SWAP, GPU, Node] 注意如果gpu获取不到将不会显示
systemResources:
  - CPU
  - RAM
  - SWAP
  - GPU
  # - Node

# 关闭图表
closedChart: false

# 是否显示FastFetch 参数:true, false, pro ,default
# true - 开启
# false - 关闭
# pro - 只有状态pro显示
# default - win默认只有pro显示，liunx等其他正常也会显示
showFastFetch: default

# 是否显示redis信息 可选参数:true, false, pro
# true - 全部显示
# false - 关闭
# pro - 只有状态pro显示
showRedisInfo: true

# Bot昵称的颜色
BotNameColor: "#000"
# Bot昵称渐变色 设置了该值BotNameColor值将无效 如要使用BotNameColor请将该值设为none或false
# 该值请参考https://developer.mozilla.org/zh-CN/docs/Web/CSS/gradient/linear-gradient
# xxdeg 为渐变角度 后为渐变颜色
# 原来花里胡哨的渐变271.14deg,#001bff 0.98%,#00f0ff 25.79%,#fce84a 47.33%,#f34628 65.77%,#b275ff 91.4%
BotNameColorGradient: "none"

#主硬件进度条和磁盘进度条的颜色
#严重
highColor: "#d73403"
#警告
mediumColor: "#ffa500"
#正常
lowColor: "#84A0DF"

# 图表配置
chartsCfg:
  themeCfg: "westeros"
  # 标题颜色
  titleColor: "#84A0DF"
  # 标题文字
  titleText: "Network"
