# 测试访问的网址列表（可空）设置为true或default将使用默认配置
# show: 是否显示 true - 显示 - false - 不显示 pro - 只有pro显示
# name: 显示名称
# url: 要访问的网址
# timeout: 测试超时时间
# useProxy: 是否使用插件配置中的代理访问
psTestSites:
    show: pro
    list:
        - name: Baidu
          url: https://baidu.com
        - name: Google
          url: https://google.com
        - name: Google(proxy)
          url: https://google.com
          useProxy: true
    timeout: 5000

# 监控任务
statusTask: true

# 如果出现内存异常的情况可将此配置项开启，如果打开后报错请将监控任务关闭
statusPowerShellStart: false

# 背景图片api，设置为false则一直使用默认背景
# CF跳板(会损失一点访问时间，但后期API地址可以自动更新)
# http://dir.dengfenglai.icu
# 默认地址(直连，但是不确定是否会GG)
# https://t.mwm.moe/mp/
backdrop: "http://dir.dengfenglai.icu"

# 当api请求失败时使用的默认背景图，请放置在resources/state/img/bg目录下
# random - 随机选择state/img/bg目录里的一张图片
# default_bg.jpg 可直接指定bg目录里一张图片，注意请带上后缀名
backdropDefault: "random"

# 关闭node的那个圈圈
closedNodeInfo: true

# 关闭图表
closedChart: false

# 是否显示FastFetch 参数:true, false, pro ,default
# true - 开启
# false - 关闭
# pro - 只有状态pro显示
# default - win默认只有pro显示，liunx等其他正常也会显示
showFastFetch: default

# Bot昵称的颜色
BotNameColor: "#000"
# Bot昵称渐变色 设置了该值BotNameColor值将无效 如要使用BotNameColor请将该值设为none或false
# 该值请参考https://developer.mozilla.org/zh-CN/docs/Web/CSS/gradient/linear-gradient
# xxdeg 为渐变角度 后为渐变颜色
# 原来花里胡哨的渐变271.14deg,#001bff 0.98%,#00f0ff 25.79%,#fce84a 47.33%,#f34628 65.77%,#b275ff 91.4%
BotNameColorGradient: "none"

#主硬件进度条和磁盘进度条的颜色
#严重
highColor: "#d73403"
#警告
mediumColor: "#ffa500"
#正常
lowColor: "#84A0DF"
