#群通知类
groupMessage: false #群消息
grouptemporaryMessage: false #群临时消息
groupRecall: false #群撤回
groupInviteRequest: false #群邀请
groupAdminChange: false #群管理变动
groupNumberChange: false #群聊列表变动
groupMemberNumberChange: false #群成员变动
addGroupApplication: false #加群申请
#好友通知类
privateMessage: false #好友消息
PrivateRecall: false #好友撤回
friendRequest: false #好友申请
friendNumberChange: false #好友列表变动
#其他通知
flashPhoto: false #闪照
botBeenBanned: false #禁言
input: false #对方正在输入
#其他设置
notificationsAll: false #全部通知
Strangers_love: false #陌生人点赞
sese: false #涩涩
state: false #状态
deltime: 600 #删除缓存
sesepro: false #涩涩增强
renderScale: 100 #渲染精度
anonymous: false #匿名
