#开启的群聊
openGroup: []
# 如需要分群，请按照下列格式添加 <以群号为字段> 的成功提示即可，0 字段代表默认回复
SuccessMsgs:
  254974507: ✅ 验证成功，欢迎入群，群里有非常多的大佬给你透哦~~
  0: ✅ 验证成功，欢迎入群

# 答案验证模式，可选：精确、模糊
mode: 精确
# 最多允许尝试次数
times: 7
# 是否开启最后一分钟提醒（仅在超时时长大于等于 120 秒时有效，true 开启，false 关闭）
remindAtLastMinute: true
# 超时时长（秒），建议至少一分钟（60 秒）
time: 300
# 随机算式的数字的随机范围
range:
  min: 10
  max: 100
