#群单独设置 会覆盖掉全局设置 全局设置可用#椰奶设置查看 或 在whole.yaml查看
123456:
  groupMessage: false #群消息
  grouptemporaryMessage: false #群临时消息
  groupRecall: false #群撤回
  groupInviteRequest: false #群邀请
  groupAdminChange: false #群管理变动
  groupNumberChange: false #群聊列表变动
  groupMemberNumberChange: false #群成员变动
  botBeenBanned: false #禁言
  flashPhoto: false #闪照

#请严格按照此格式 不需要的设置项可删除
123456:
  groupMessage: false #群消息
  grouptemporaryMessage: false #群临时消息
