#注：修改后重启生效，请严格按照yaml语法进行修改，否则会出现意料之外的错误

mode: true #指令匹配模式 true为精确匹配，false为模糊匹配
#key值设置为要触发的词
bs:
  url: http://api.caonm.net/api/bhs/b.php #在url字段后面写接口链接

  type: image
  #根据接口指定类型类型包括 image text json 如不写则默认为image
  # image指接口直接返回图片
  # text指接口返回链接
  # json指接口返回json字符串 ,返回json需指定path请参考以下json示例

#也可以以"|"分隔设置多个触发词
hs|黑丝|heisi:
  url:
    - http://api.caonm.net/api/bhs/h.php
    - http://api.starrobotwl.com/api/heisi.php #可以采用这种格式进行一个关键词设置多个链接
      #或者["http...", "http..."]这种格式，可百度"yaml配置数组写法"参考

#返回json示例
ecy:
  url: https://sex.nyan.xyz/api/v2/
  type: json
  path: data[0].url #接口返回链接在 "data数组" 里面用 "[0]" 来指定数组的第几个值后再 ".url" 即可，最后必须指向图片链接

#返回text示例
meizi:
  url: https://xiaobapi.top/api/xb/api/meizi.php
  type: text

bm:
  url: http://iw233.cn/api.php?sort=yin #在url字段后面写链接，仅限直接返回图片的api

sy: https://iw233.cn/api.php?sort=cat #或者直接写链接效果同上，仅限直接返回图片的api
